apiVersion: v1
kind: Service
metadata:
  name: minecraftc-service
  labels:
    app: static
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 25565
    protocol: TCP
    targetPort: 25565
  selector:
    app: static
  sessionAffinity: None
  type: LoadBalancer
